### PR TITLE
General cleanup and readme improvements

### PR DESCRIPTION
**Pull request by OgelGames**
I'm just going to leave this here.

@BuckarooBanzay @S-S-X @wsor4035

### CODE REVIEW

**Comment by wsor4035** [comment]
buckaroo did just agree to there readme docs being under MIT, so that is fine now

**Comment by wsor4035** [comment]
also it appears (at least on github) this is mixing two/four spaces/tabs

**Comment by wsor4035** [comment]
latest commit didnt address the readme

**Comment by OgelGames** [comment]
So, is this okay to merge now?

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay @S-S-X @wsor4035

a bit too late but yeah, lgtm :upside_down_face:

**Pull request merged**
